name: mini-javascript
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - array

library:
  source-dirs: src

build-tools:
  - alex
  - happy

executables:
  MJS:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mini-javascript
      - repline
      - mtl
      - text
